### ISSUE TITLE
Stuck on "Waiting Result from OpenAPI "

### ISSUE THREAD

**Issue by dgrivera** [hisxo/ReconAIzer#13]
Burp Version: v2023.6.2
Extension Version: v0.7

![image](https://github.com/hisxo/ReconAIzer/assets/18552695/cefa666f-0164-4bf4-a3d2-e06c8800ded1)

**Comment by dgrivera** [comment]
here is the error:

at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:420)

at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:709)

at java.base/java.lang.reflect.Method.invoke(Method.java:569)

java.lang.IllegalAccessException: java.lang.IllegalAccessException: class org.python.core.PyReflectedFunction cannot access class sun.net.www.protocol.https.HttpsURLConnectionImpl (in module java.base) because module java.base does not export sun.net.www.protocol.https to unnamed module @417381c1

at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:420)

at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:709)

at java.base/java.lang.reflect.Method.invoke(Method.java:569)

java.lang.IllegalAccessException: java.lang.IllegalAccessException: class org.python.core.PyReflectedFunction cannot access class sun.net.www.protocol.https.HttpsURLConnectionImpl (in module java.base) because module java.base does not export sun.net.www.protocol.https to unnamed module @417381c1

**Comment by Seraphice** [comment]
I had the same problem

**Comment by Matin7697** [comment]
i had this problem also

**Comment by hisxo** [comment]
Hell everyone,

I will take a look and see if I can fix it! :)

Cheers

**Comment by tooba17-glitch** [comment]
@hisxo is the issue resolved? because I'm getting same "Waiting results from OpenAI... "

**Comment by 0xsheet** [comment]
same problem any one fix?
