### ISSUE TITLE
Does not work after install

### ISSUE THREAD

**Issue by blackblastie** [hisxo/ReconAIzer#9]
I am trying to install and use this extension, but after installing (appears to be successful), the tab is unresponsive and shows nothing in it. I tried sending a request to it, but still nothing showing. I installed other custom python extensions successfully, so I don't think there is an issue with the jython file. 

![image](https://user-images.githubusercontent.com/13769840/235273344-7ed1353e-e6eb-4eff-abe5-1006f177d128.png)
![image](https://user-images.githubusercontent.com/13769840/235273199-61e0de63-fb22-4674-9407-837730eec764.png)

**Comment by hisxo** [comment]
Could you try the latest version and to configure your API key also? Let me know if you still have issue

Also please check the extension output on extension tab

**Comment by blackblastie** [comment]
I've installed the latest a handful of times, and there is no config tab being rendered for me to enter the API key.

**Comment by hisxo** [comment]
Which version of burp are you using?

**Comment by 0xsheet** [comment]
same problem

error is show ?

Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\ReconAIzer.v0.7.py", line 132, in run
    api_result = self.extender.send_request_to_openai(text, self.prompt_type)
  File "C:\Users\Admin\Desktop\ReconAIzer.v0.7.py", line 205, in send_request_to_openai
    raise Exception("Exceeded maximum retries for API request")
Exception: Exceeded maximum retries for API request
